# Generated by Django 5.2.3 on 2025-06-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_telegramuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='Подписан на канал'),
        ),
    ]
