# Generated by Django 5.2.3 on 2025-06-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='broadcasts', to='shop.telegramuser', verbose_name='Получатели'),
        ),
    ]
